# Generated by Django 5.0.4 on 2024-04-16 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyBlogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titles', models.CharField(max_length=100)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('taa', models.CharField(max_length=100)),
                ('image', models.TextField()),
                ('views', models.IntegerField(default=10)),
            ],
        ),
    ]
